#!/bin/bash

# Create symbolic links from home directory to rcfiles in this script's directory

this="$(basename $0)"
dirname=$(dirname $0)
if [ "${dirname:0:1}" == "/" ]; then
    cwd=$(dirname $0)
else
    cwd=$(pwd)/$(dirname $0)
fi

for rcfile in $cwd/* $cwd/host/$(hostname)/*; do
    rcfile_base=$(basename "$rcfile")
    if [ \( -f $rcfile \) \
	-a  \( "$rcfile_base" != "$this" \) \
	-a \( "${rcfile_base:(-1)}" != "~" \) ]; then
	echo $rcfile
	ln -sf $(dirname $rcfile)/$rcfile_base ~/.$rcfile_base
    fi
done
