#!/bin/sh

this="$(basename $0)"

for rcfile in $(dirname $0)/*; do
    rcfile_base=$(basename "$rcfile")
    if [ \( "$rcfile_base" != "$this" \) -a \( "${rcfile_base:(-1)}" != "~" \) ]; then
	echo ln -sf $(dirname $0)/$rcfile_base ~/$rcfile_base
    fi
done
