#!/bin/bash

# Create symbolic links from home directory to rcfiles in this script's directory

this="$(basename $0)"
dirname=$(dirname $0)
if [ "${dirname:0:1}" == "/" ]; then
    cwd=$(dirname $0)
else
    cwd=$(pwd)/$(dirname $0)
fi

for rcfile in $(dirname $0)/*; do
    rcfile_base=$(basename "$rcfile")
    if [ \( "$rcfile_base" != "$this" \) -a \( "${rcfile_base:(-1)}" != "~" \) ]; then
	echo $rcfile_base
	ln -sf ${cwd}/$rcfile_base ~/.$rcfile_base
    fi
done
